age_str = input("Please tell me your age: ").strip()
age =int(age_str)
print(f"You are {age} years old.")
print(f"In 10 years you will be {age+10} years old.")
print(f"In 20 years you will be {age+20} years old.")
print(f"In 20 years you will be {age+30} years old.")
